# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoIT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoIT
  pod 'SQLite.swift', '~> 0.11.5'
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'DoITTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DoITUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
